name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if deploying from another branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures PaperMod submodule is cloned

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Hugo (v0.146.0 or greater)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.0'  # Ensure compatibility with PaperMod
          extended: true  # Required for SCSS processing (PaperMod uses this)

      - name: Build Hugo Site
        run: hugo --minify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
